config/routes.rb
Sixcard::Application.routes.draw do
  root to: "welcome#index"

  # Sign up
  get "sign_up" => "users#new"

  # Sign in/out
  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  delete "sign_out" => "sessions#destroy"

  # Following is superceded by the above routes
  # resource :session, only: [:new, :create, :destroy]

  resources :users
  
  resources :decks, only: [:index, :new, :create, :show] do
    resources :cards, only: [:new, :create, :show]
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :decks
  validates :email, 
    uniqueness: true,
    format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    if cookies[:email]
      @current_user ||= User.find_by_email(cookies.signed[:email])
    end
  end
  helper_method :current_user
  
  def sign_in user
    cookies.signed.permanent[:email] = user.email
  end

  def signed_in?
    current_user
  end
  helper_method :signed_in?

  def authenticate
    redirect_to root_path, notice:"You need to be signed in" unless signed_in?
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :authenticate

  def new
    @deck = current_user.decks.find(params[:deck_id])
    @card = Card.new
  end

  def create  
    @deck = current_user.decks.find(params[:deck_id])
    @card = @deck.cards.build(params[:card])
    @card.save  
    redirect_to @deck, notice: "Card Saved"
  end

  def show
    @deck = current_user.decks.find(params[:deck_id])
    @card = @deck.cards.find(params[:id])
  end
  
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_filter :authenticate

  def index
    @decks = current_user.decks
  end
  
  def new
    @deck = Deck.new
  end

  def create
    @deck = current_user.decks.new(params[:deck])
    if @deck.save
      redirect_to decks_path, notice: "Deck Saved"
    else
      render "new"
    end
  end

  def show
    @deck = Deck.find(params[:id])
    @cards = @deck.cards
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end


  def create
    if user = User.where(email: params[:session][:email]).first
      sign_in(user)
      redirect_to root_path, notice: "Signed in successfully"
    else
      flash.now[:notice] = "Invalid user"
      render action: "new"
    end
  end
  
  def destroy
    cookies.delete(:email)
    redirect_to root_path, notice: "Signed out successfully"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in(@user)
      redirect_to decks_path, notice: "Thanks for signing up!"
    else
      render "new"
    end
  end    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :redirect_to_decks_if_signed_in

  def redirect_to_decks_if_signed_in
    redirect_to decks_path, notice:"Welcome to your decks" if signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/index.html.erb
<%= link_to 'Create card', new_deck_card_path(@deck) %>
<ul>
<% @cards.each do |card| %>
  <li><%= link_to card.front, [@deck, card] %></li>
<% end  %>
</ul>

app/views/cards/new.html.erb
<%= form_for([@deck,@card]) do |form| %>

<div>
  <%= form.label :front %>
  <%= form.text_field :front %>
</div>

<div>
  <%= form.label :back %>
  <%= form.text_field :back %>
</div>

<%= form.submit %>

<% end %>

app/views/cards/show.html.erb
<div> 
<%= @card.back %>
</div>

<%= link_to "Back", @deck %>

app/views/decks/_deck.html.erb
<li><%= link_to deck.name, deck %></li>

app/views/decks/index.html.erb
<h1>Decks</h1>
<%= link_to 'New deck', new_deck_path %>
<ul>
  <%= render @decks %>
</ul>

app/views/decks/new.html.erb
<%= form_for(@deck) do |form| %>
<% if @deck.errors.any? %>
  <p>There was an issue.</p>
  <ul>
  <% @deck.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

<% end %>
<div>
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
<%= form.submit %>
<% end %>

app/views/decks/show.html.erb
<h1> 
<%= @deck.name %>
</h1>
<%= link_to 'Create card', new_deck_card_path(@deck) %>
<ul>
<% @cards.each do |card| %>
  <li><%= link_to card.front, [@deck, card] %></li>
<% end  %>
</ul>
<%= link_to "Back", decks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sixcard</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :javascripts %>
</head>
<body>
<% if current_user %>
<p>Welcome <%= current_user.email %> :: <%= link_to 'Sign Out', sign_out_path, :confirm => 'Are you sure?', :method => :delete %></p>
<% elsif %>
<%= link_to 'Sign in', sign_in_path %>
<% end %>

<% if notice %>
<p class="notice"><%= notice %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for(@user) do |form| %>
<% if @user.errors.any? %>
  <p>There was an issue.</p>
  <ul>
  <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

<div>
  <%= form.label :email %>
  <%= form.text_field :email %>
</div>

<%= form.submit %>

<% end %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<%= link_to 'New user', sign_up_path %>